tap "aws/tap"
tap "fluxcd/tap"
tap "github/gh"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "kudobuilder/tap"
tap "moncho/dry"
tap "robotsandpencils/made"
tap "stripe/stripe-cli"
tap "ubuntu/microk8s"
brew "ack"
brew "act"
brew "adns"
brew "gdbm"
brew "openssl@1.1"
brew "readline"
brew "sqlite"
brew "xz"
brew "afflib"
brew "ahoy"
brew "libgpg-error"
brew "libgcrypt"
brew "pcre"
brew "aide"
brew "anyenv"
brew "argo"
brew "argocd"
brew "gettext"
brew "libffi"
brew "glib"
brew "python@3.8"
brew "atk"
brew "augeas"
brew "autoconf"
brew "automake"
brew "autossh"
brew "awslogs"
brew "awsweeper"
brew "azure-cli"
brew "icu4c"
brew "c-ares"
brew "jemalloc"
brew "libev"
brew "libuv"
brew "nghttp2"
brew "node"
brew "balena-cli"
brew "bartycrouch"
brew "bash-completion"
brew "bat"
brew "openjdk"
brew "bfg"
brew "black"
brew "boost"
brew "boost-python3"
brew "buildkit"
brew "caf"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "pkg-config"
brew "lzo"
brew "pixman"
brew "cairo"
brew "libsigc++"
brew "cairomm"
brew "libsigc++@2"
brew "catimg"
brew "eigen"
brew "gmp"
brew "mpfr"
brew "cgal"
brew "chamber"
brew "checkstyle"
brew "chrome-cli"
brew "cli53"
brew "cmake"
brew "composer"
brew "coreutils"
brew "cortex"
brew "csvkit"
brew "ctags"
brew "ctop"
brew "libunistring"
brew "libidn2"
brew "libssh2"
brew "zstd"
brew "curl"
brew "dbhash"
brew "dbus"
brew "go"
brew "dep"
brew "dependency-check"
brew "dhall"
brew "dhall-bash"
brew "dhall-json"
brew "dhall-lsp-server"
brew "dhall-yaml"
brew "dialog"
brew "diff-so-fancy"
brew "digdag"
brew "direnv"
brew "diskonaut"
brew "dive"
brew "geoip"
brew "ssdeep"
brew "dnstwist"
brew "docbook"
brew "docbook-xsl"
brew "docker-credential-helper-ecr", link: false
brew "docker-ls"
brew "docker-machine"
brew "docker-machine-driver-hyperkit"
brew "docker-machine-driver-xhyve"
brew "docker-squash"
brew "doitlive"
brew "dos2unix"
brew "doxygen", link: false
brew "e2fsprogs"
brew "ec2-api-tools"
brew "pcre2"
brew "editorconfig"
brew "eject"
brew "elvish"
brew "envconsul"
brew "exa"
brew "exercism"
brew "expat"
brew "fd"
brew "fribidi"
brew "libtool"
brew "libevent"
brew "libtasn1"
brew "nettle"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "graphite2"
brew "harfbuzz"
brew "jpeg"
brew "libtiff"
brew "little-cms2"
brew "openjpeg"
brew "webp"
brew "libsodium"
brew "snappy"
brew "x265"
brew "zeromq"
brew "ffsend"
brew "libmagic"
brew "file-formula"
brew "flex"
brew "fluxctl"
brew "fn"
brew "libidn"
brew "gnu-getopt"
brew "ilmbase", link: true
brew "libde265"
brew "xmlto"
brew "shared-mime-info"
brew "libheif"
brew "liblqr"
brew "libomp"
brew "imagemagick"
brew "folderify"
brew "gflags"
brew "glog"
brew "lz4"
brew "fonttools"
brew "fortio"
brew "fortune"
brew "fping"
brew "fswatch"
brew "gammu"
brew "gawk"
brew "isl"
brew "libmpc"
brew "gcc"
brew "gd"
brew "gdk-pixbuf"
brew "gdm"
brew "geckodriver"
brew "getdns"
brew "gh"
brew "git"
brew "git-credential-manager"
brew "git-extras"
brew "git-flow-avh"
brew "git-lfs"
brew "libassuan"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "git-secret"
brew "gitleaks"
brew "libgit2"
brew "gitless"
brew "gitmoji"
brew "glances"
brew "glide"
brew "gnu-sed"
brew "godep"
brew "goenv"
brew "golang-migrate"
brew "google-sparsehash"
brew "gowsdl"
brew "gsettings-desktop-schemas"
brew "hicolor-icon-theme"
brew "libepoxy"
brew "pango"
brew "gtk+3"
brew "librsvg"
brew "openblas"
brew "numpy"
brew "py3cairo"
brew "pybind11"
brew "pygobject3"
brew "scipy"
brew "graph-tool"
brew "jasper"
brew "netpbm"
brew "gts"
brew "graphviz"
brew "gron"
brew "grpcurl"
brew "openjdk@11"
brew "gssh"
brew "gtk+"
brew "helm"
brew "helm@2"
brew "helmfile"
brew "howdoi"
brew "ncurses"
brew "htop"
brew "http-parser"
brew "httpflow"
brew "httpie"
brew "httping"
brew "httpx"
brew "hub"
brew "hugo"
brew "imagemagick@6"
brew "infracost"
brew "intltool"
brew "ipython"
brew "ispell"
brew "jansson"
brew "oniguruma"
brew "jq"
brew "json-glib"
brew "jsoncpp"
brew "jsonnet"
brew "jsonpp"
brew "pandoc"
brew "jupyterlab"
brew "just"
brew "k9s"
brew "krb5"
brew "krew"
brew "kubeaudit"
brew "kubecfg"
brew "kubecm"
brew "kubectx"
brew "kubeprod"
brew "kubeseal"
brew "kubespy"
brew "landscaper"
brew "lego"
brew "leiningen"
brew "libb2"
brew "libarchive"
brew "libcroco"
brew "libelf"
brew "libewf"
brew "libplist"
brew "libusbmuxd"
brew "libimobiledevice"
brew "libkeccak"
brew "libmaxminddb"
brew "libpq"
brew "lzlib"
brew "librdkafka"
brew "libressl"
brew "libsmi"
brew "libssh"
brew "unibilium"
brew "libtermkey"
brew "libusb-compat"
brew "libvterm"
brew "libyaml"
brew "libzip"
brew "linkerd"
brew "lldpd"
brew "lmod"
brew "lorem"
brew "lua@5.1", link: false
brew "luajit"
brew "luarocks"
brew "lynis"
brew "magic-wormhole"
brew "makedepend"
brew "utf8proc"
brew "mame"
brew "mas"
brew "mdcat"
brew "microplane"
brew "miller"
brew "minisign"
brew "protobuf"
brew "mitmproxy"
brew "mkcert"
brew "mmark"
brew "mono", link: false
brew "moreutils"
brew "msgpack"
brew "mussh"
brew "mycli"
brew "mysql-client"
brew "ncftp"
brew "neovim"
brew "newman"
brew "nginx"
brew "ngs"
brew "nspr"
brew "nss", link: false
brew "ocrmypdf"
brew "openapi-generator"
brew "pkcs11-helper"
brew "openvpn"
brew "operator-sdk"
brew "packer"
brew "packer-completion"
brew "packetbeat"
brew "pdsh"
brew "perl"
brew "pgcli"
brew "pgformatter"
brew "pidof"
brew "pmd"
brew "popt"
brew "postgresql"
brew "prettier"
brew "prips"
brew "procs"
brew "proselint"
brew "protobuf-c"
brew "prototool"
brew "pspg"
brew "pssh"
brew "pth"
brew "pwgen"
brew "py2cairo"
brew "pyinvoke"
brew "qt"
brew "quicktype"
brew "rakudo-star"
brew "rapidjson"
brew "rclone"
brew "re2c"
brew "regina-rexx"
brew "reposurgeon"
brew "rlwrap"
brew "rmlint"
brew "rom-tools"
brew "rpg-cli"
brew "rust"
brew "rust-analyzer"
brew "s-lang"
brew "scons"
brew "scw"
brew "sd"
brew "semgrep"
brew "servus"
brew "sha3sum"
brew "shadowenv"
brew "shfmt"
brew "ship"
brew "shmux"
brew "skaffold"
brew "slackcat"
brew "sleuthkit"
brew "socat"
brew "sops"
brew "sourcedocs"
brew "sourcery"
brew "speedtest-cli"
brew "sphinx-doc"
brew "sqlite-analyzer"
brew "sqlmap"
brew "sslscan"
brew "starship"
brew "step"
brew "stern"
brew "stormssh"
brew "stormssh-completion"
brew "stunnel"
brew "subversion"
brew "supervisor"
brew "swift-sh"
brew "tbb"
brew "sysdig"
brew "talisman"
brew "thanos"
brew "thrift"
brew "tmux"
brew "tmuxinator-completion"
brew "topgrade"
brew "tox"
brew "transmission-cli"
brew "trash"
brew "tunnel"
brew "typescript", link: false
brew "unixodbc"
brew "unzip"
brew "uriparser"
brew "vapor"
brew "vault-cli"
brew "velero"
brew "wandio"
brew "watch"
brew "watchman"
brew "websocat"
brew "wget"
brew "wireshark"
brew "wsk"
brew "wxwidgets"
brew "xerces-c"
brew "xmlstarlet"
brew "xonsh"
brew "yadm"
brew "yajl"
brew "yamllint"
brew "yara"
brew "ydiff"
brew "yj"
brew "yq"
brew "zeek"
brew "zlib"
brew "zorba"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "zsh-navigation-tools"
brew "zsh-syntax-highlighting"
brew "zurl"
brew "fluxcd/tap/flux"
brew "jesseduffield/lazygit/lazygit"
brew "kudobuilder/tap/kudo-cli"
brew "moncho/dry/dry"
brew "robotsandpencils/made/xcodes"
brew "stripe/stripe-cli/stripe"
cask "0-ad"
cask "1password"
cask "1password-cli"
cask "acorn"
cask "adobe-acrobat-reader"
cask "adoptopenjdk"
cask "adoptopenjdk8"
cask "backblaze"
cask "backblaze-downloader"
cask "balenaetcher"
cask "battle-net"
cask "bbedit"
cask "crossover"
cask "daisydisk"
cask "discord"
cask "dotnet"
cask "doxygen"
cask "drivethrurpg"
cask "emacs"
cask "firefox"
cask "fluid"
cask "font-acme"
cask "font-almendra"
cask "font-anonymous-pro"
cask "font-bebas-neue"
cask "font-bitstream-vera-sans-mono-nerd-font"
cask "font-bitter"
cask "font-cinzel"
cask "font-consolas-for-powerline"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-montserrat"
cask "font-open-dyslexic-nerd-font"
cask "font-oxygen-mono"
cask "font-powerline-symbols"
cask "font-pt-mono"
cask "font-quicksand"
cask "font-raleway"
cask "font-slabo-13px"
cask "font-source-code-pro"
cask "font-ubuntu-mono-nerd-font"
cask "font-ubuntu-nerd-font"
cask "fork"
cask "fs-uae"
cask "gog-galaxy"
cask "google-cloud-sdk"
cask "graphiql"
cask "handbrake"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "java11"
cask "jetbrains-toolbox"
cask "jupyter-notebook-ql"
cask "jupyter-notebook-viewer"
cask "leech"
cask "lens"
cask "libreoffice"
cask "little-snitch"
cask "logitech-options"
cask "logitech-unifying"
cask "mactex"
cask "marsedit"
cask "mcedit"
cask "minecraft"
cask "nova"
cask "obs"
cask "obs-virtualcam"
cask "oracle-jdk"
cask "oxygen-xml-editor"
cask "postman"
cask "rectangle"
cask "scrivener"
cask "shotcut"
cask "slack"
cask "soulver"
cask "ssh-tunnel-manager"
cask "steam"
cask "superduper"
cask "tableplus"
cask "transmission"
cask "tunnelblick"
cask "twine"
cask "unetbootin"
cask "visual-studio-code-insiders"
cask "waterfox-current"
cask "zerotier-one"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Bear", id: 1091189122
mas "Bear", id: 1091189122
mas "Bible Study", id: 472790630
mas "Bible Study", id: 472790630
mas "Bible Study", id: 472790630
mas "Bible Study", id: 472790630
mas "DaisyDisk", id: 411643860
mas "Developer", id: 640199958
mas "Developer", id: 640199958
mas "Fantastical", id: 975937182
mas "Fastest VPN", id: 1480208488
mas "GarageBand", id: 682658836
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "HaTTiP", id: 828152861
mas "iMovie", id: 408981434
mas "iMovie", id: 408981434
mas "iPulse", id: 1028916583
mas "Key Codes", id: 414568915
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Keynote", id: 409183694
mas "Linguan", id: 477163052
mas "Linguan", id: 477163052
mas "Numbers", id: 409203825
mas "Numbers", id: 409203825
mas "Numbers", id: 409203825
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pages", id: 409201541
mas "Pages", id: 409201541
mas "Pages", id: 409201541
mas "PaintCode", id: 808809998
mas "PaintCode", id: 808809998
mas "PDF OCR X Community Edition", id: 571442933
mas "PDF OCR X Community Edition", id: 571442933
mas "Prepo", id: 476533227
mas "Prepo", id: 476533227
mas "Proelia", id: 515732997
mas "Proelia", id: 515732997
mas "Proelia", id: 515732997
mas "Proelia", id: 515732997
mas "Proelia", id: 515732997
mas "Realm Browser", id: 1007457278
mas "Realm Browser", id: 1007457278
mas "Receigen", id: 452840086
mas "Receigen", id: 452840086
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "Soulver", id: 413965349
mas "Spark", id: 1176895641
mas "Spark", id: 1176895641
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
mas "Xcode", id: 497799835
mas "xScope", id: 447661441
mas "xScope", id: 447661441
mas "xScope", id: 447661441
